repos:
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
      - id: mypy
        name: mypy services
        files: ^services/
      - id: mypy
        name: mypy providers
        files: ^providers/
      - id: mypy
        name: mypy scheduler
        files: ^scheduler/
      - id: mypy
        name: mypy bot handlers
        files: ^bot/file_handlers.py$
      - id: mypy
        name: mypy admin
        files: ^bot/admin.py$
      - id: mypy
        name: mypy error middleware
        files: ^bot/error_middleware.py$
      - id: mypy
        name: mypy logging config
        files: ^logging_config.py$
      - id: mypy
        name: mypy strict gemini
        files: ^providers/gemini.py$
        args: [--strict, --ignore-missing-imports, --follow-imports=skip, --disable-error-code=misc]
      - id: mypy
        name: mypy strict admin router
        files: ^bot/admin.py$
        args: [--strict, --ignore-missing-imports, --follow-imports=skip, --disable-error-code=misc]
  - repo: local
    hooks:
      - id: dockerfilelint
        name: dockerfilelint
        entry: bash -c 'npx dockerfilelint "$@" || true'
        language: node
        types: ["dockerfile"]
      - id: hadolint
        name: hadolint
        entry: bash -c 'hadolint "$@" || true'
        language: system
        types: ["dockerfile"]
      - id: pip-check
        name: pip-check
        entry: pip check
        language: system

