version: '3.9'
services:
  bot:
    build: ..
    volumes:
      - ../data:/app/data
    env_file: ../.env
    restart: on-failure
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "python", "-m", "bot.main", "--ping"]
      interval: 10s
      timeout: 3s
      retries: 5

