version: '3.8'
services:
  bot:
    build:
      context: ..
    volumes:
      - ../data:/app/data
    env_file: ../.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-m", "bot.main", "--ping"]
      interval: 30s
      timeout: 10s
      retries: 3
