services:
  bot:
    build:
      context: .
      target: builder
    image: tgbot:dev
    env_file: .env
    environment:
      - DB_PATH=${DB_PATH}
    volumes:
      - ./data:/app/data
    ports:
      - "8080:8080"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-m", "bot.main", "--ping"]
      interval: 30s
      start_period: 30s
      retries: 3

