services:
  bot:
    build: ..
    env_file: ../.env
    environment:
      TZ: Europe/Berlin
    volumes:
      - ../data:/app/data
    ports:
      - "8080:8080"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/ping || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
