services:
  bot:
    image: ghcr.io/example/tgbot:latest
    container_name: bot
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
    volumes:
      - ./data:/app/data
    ports:
      - "8080:8080"
    restart: always
    healthcheck:
      test: ["CMD", "python", "-m", "bot.main", "--ping"]
      interval: 30s
      start_period: 30s
      retries: 3
