name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install deps
        run: pip install -r requirements.txt pre-commit "httpx[socks]"
      - name: DB tests
        run: pytest -q tests/db
      - name: Lint
        run: pre-commit run --all-files
      - name: Test
        run: pytest -q
      - name: Docker dry-run
        run: docker build -t bot:test .
