name: CI
on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Run lint
        run: pre-commit run --all-files

      - name: Run tests
        env:
          BOT_TOKEN: 123456:FAKE-TOKEN-FOR-CI
        run: python -m pytest -q

      - name: Docker build
        run: docker build -t bot:test .
