name: CI
on: [ push, pull_request ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Клонируем репозиторий
      - uses: actions/checkout@v4

      # 2. Устанавливаем Python 3.11
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 3. Устанавливаем зависимости
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      # 4. Прогоняем тесты
      - name: Run tests
        env:
          BOT_TOKEN: 123456:FAKE-TOKEN-FOR-CI
        run: python -m pytest -q
